export const skillCategories = [
  {
    title: "Frontend",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Tailwind CSS",
      "Framer Motion",
    ],
  },
  {
    title: "Backend",
    skills: [
      "Node.js",
      "Express",
      "FastAPI",
      "MongoDB",
      "PostgreSQL",
      "RESTful APIs",
      "GraphQL",
      "JWT",
    ],
  },
  {
    title: "AI Development",
    skills: [
      "LangChain",
      "LangGraph",
      "RAG (Retrieval-Augmented Generation)",
      "AI Agents",
      "OpenAI API",
      "Hugging Face",
      "LLMs Integration",
      "AI Automation",
      "Vector Databases",
      "Full-Stack AI Solutions",
    ],
  },
  {
    title: "Chatbots",
    skills: [
      "Custom AI Chatbots",
      "WhatsApp Chatbots",
      "Dialogflow",
      "Twilio API",
      "ChatGPT API",
      "Multichannel Automation",
    ],
  },
  {
    title: "Tools & Others",
    skills: [
      "Git",
      "GitHub",
      "VS Code",
      "Figma",
      "Postman",
      "Linux",
      "Docker",
      "Vercel",
      "Netlify",
      "Render",
    ],
  },
  {
    title: "Soft Skills",
    skills: [
      "Problem Solving",
      "Team Collaboration",
      "Communication",
      "Time Management",
      "Adaptability",
      "Critical Thinking",
    ],
  },
];